# Generated by Django 2.1 on 2019-02-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authon',
            new_name='author',
        ),
    ]
